### ISSUE TITLE
model.load_state_dict(torch.load('Models/model_epoch_2', map_location=device))

### ISSUE THREAD

**Issue by swadhin7** [Aftaab99/OfflineSignatureVerification#1]
While running test.py error related to model.load_state_dict(torch.load('Models/model_epoch_2', map_location=device)) is showing .

Error: FileNotFoundError: [Errno 2] No such file or directory: 'model_epoch_%d'

**Comment by Aftaab99** [comment]
@swadhin7 You'll have to download the pretrained model and place it in the Models(you'll have to create one) directory. Link in the README.

**Comment by Aftaab99** [comment]
Thank you for raising this issue. There actually a bug in Test.py but it was not related to issue you were stating. You can resolve by doing what I said above.
Closing the issue.
