### ISSUE TITLE
invalid load key, '\xef'.

### ISSUE THREAD

**Issue by adishijha** [Aftaab99/OfflineSignatureVerification#11]
Server error in VS code

**Comment by Aftaab99** [comment]
Just tried running the project again, just to confirm. Its working fine for me.
Most probably the pretrained model that got downloaded got corrupted for some reason, [as others who encountered this](https://github.com/leftthomas/ESPCN/issues/6#issuecomment-583103554) say. 

Try deleting the `Models/` directory and running `DownloadData.py` again. I'm not really able to reproduce this error, and most probably its just a issue of the file being corrupted.

Also make you sure you are using a version of PyTorch 0.4.1(or above) and Python3.5+.

Thanks for reporting. Feel free to reopen the issue if need be.
