### ISSUE TITLE
pre trained model

### ISSUE THREAD

**Issue by Jatin-kaushik** [Aftaab99/OfflineSignatureVerification#14]
hi aftab i tried ur pre trained model on my dataset, but it giving me match = true on every verification pic. I tried on real, forge and fake data and reduce threshold too but nothing work 
![00100001](https://user-images.githubusercontent.com/62387170/117263574-08138800-ae70-11eb-80bc-cd8538d3bddd.png) 
real
![00101001](https://user-images.githubusercontent.com/62387170/117263579-0944b500-ae70-11eb-91ed-1ef8344c7a1f.png)
real
![00102001](https://user-images.githubusercontent.com/62387170/117263584-09dd4b80-ae70-11eb-8026-534d3ed7f8ab.png)
real
![00200002](https://user-images.githubusercontent.com/62387170/117263623-12358680-ae70-11eb-8139-d59d117e855f.png)
fake
![02100001](https://user-images.githubusercontent.com/62387170/117263644-1bbeee80-ae70-11eb-84b0-fc5640d5437b.png)
forge
![02101001](https://user-images.githubusercontent.com/62387170/117263652-1cf01b80-ae70-11eb-9e97-bd9120480655.png)
forge
![02102001](https://user-images.githubusercontent.com/62387170/117263655-1cf01b80-ae70-11eb-8e82-a2d31d29d566.png)
forge
 can u please check and if you have new saved model can u please give link with threshold value.
 Thank you.

**Comment by Aftaab99** [comment]
Threshold value for the pretrained model is available in the code.
Model can be downloaded by running the `DownloadData.py` file as mentioned in the Readme.
