### ISSUE TITLE
PARAM SIZE MISMATCH

### ISSUE THREAD

**Issue by DanielGeorgeMathew** [Aftaab99/OfflineSignatureVerification#3]
RuntimeError: Error(s) in loading state_dict for SiameseConvNet:
        Unexpected key(s) in state_dict: "conv4.weight", "conv4.bias", "fc1.bias", "fc2.bias".
        size mismatch for conv1.weight: copying a param with shape torch.Size([48, 1, 11, 11]) from checkpoint, the shape in current model is torch.Size([5, 1, 11, 11]).
        size mismatch for conv1.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([5]).
        size mismatch for conv2.weight: copying a param with shape torch.Size([128, 48, 5, 5]) from checkpoint, the shape in current model is torch.Size([12, 5, 5, 5]).
        size mismatch for conv2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for conv3.weight: copying a param with shape torch.Size([256, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 12, 3, 3]).
        size mismatch for conv3.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([16]).
        size mismatch for fc1.weight: copying a param with shape torch.Size([1024, 40800]) from checkpoint, the shape in current model is torch.Size([1024, 28560]).

Im getting this error in the torch.load call

**Comment by Aftaab99** [comment]
Seems you have cloned the repo before the last commit and the script has downloaded the previous version of the model. Try deleting model file and running DownloadData.py again, that should download the current model. This doesn't seem to be a issue with the code, so I'm closing the issue. Please do re-open it if in case you still encounter the error.
Thanks.

**Comment by DanielGeorgeMathew** [comment]
You are right.. Thanks for the response
